##### BASIC #####

# Prefix (lebih enak dari C-b)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Shell
set -g default-shell /usr/bin/zsh

# Mouse support
set -g mouse on

# Window & pane index mulai dari 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# History
set -g history-limit 5000

# Escape time (biar vim ga delay)
set -sg escape-time 10


##### SPLIT #####

# Split shortcut
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Resize pane (vim-like)
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

##### TOKYO NIGHT MOON THEME #####

# Status bar
set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-style "bg=#222436,fg=#c8d3f5"

# Left status
set -g status-left "#[bg=#82aaff,fg=#1b1d2b,bold]  #S #[bg=default,fg=default] "
set -g status-left-length 40

# Right status
set -g status-right "#[fg=#ffc777] %H:%M #[fg=#c099ff] %d-%b-%y "
set -g status-right-length 50

# Window list
setw -g window-status-style fg=#82aaff,bg=#222436
setw -g window-status-current-style fg=#1b1d2b,bg=#c099ff,bold
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "

# Pane border
set -g pane-border-style fg=#2f334d
set -g pane-active-border-style fg=#82aaff

# Message (Command line)
set -g message-style bg=#ffc777,fg=#1b1d2b,bold

##### COPY MODE (VIM STYLE) #####

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel


##### PLUGINS #####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'


# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
